spring:
  profiles:
    include: log

  cloud:
    config:
      discovery:
        enabled: true

  zipkin:
    sender:
      type: web
  sleuth:
    web:
      client:
        enabled: true

  devtools:
    restart:
      log-condition-evaluation-delta: false

eureka:
  instance:
    prefer-ip-address: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

feign:
  hystrix:
    enabled: true

