server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhangColin/cartisan-config-repository.git
          username: ZhangColin
          password: Zh@ng_C0lin
          basedir: /Users/colin/Workspace/cartisan-config-repository
eureka:
  client:
    service-url:
      # 这个注册是通过容器编排来查找的，所以名称是容器名称，不是注册中心应用的名称
      defaultZone: http://www.hsqjp.com:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
