server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZhangColin/cartisan-config-repository.git
          username: ZhangColin
          password: Zh@ng_C0lin
          basedir: /Users/colin/Workspace/cartisan-config-repository
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
