### 获取所有品牌列表
GET http://localhost:9002/brands
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 获取品牌
GET http://localhost:9002/brands/1
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 搜索品牌（不带参数）
GET http://localhost:9002/brands/search/1/10
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 搜索品牌
GET http://localhost:9002/brands/search/1/10?name=car
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 添加品牌
POST http://localhost:9002/brands
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "cartisan111",
  "firstLetter": "C",
  "isManufacturer": true,
  "isShow": true,
  "logo": "logo",
  "bigPic": "bigPic",
  "sort": 100
}

### 更新品牌
PUT http://localhost:9002/brands/11
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "cartisan",
  "firstLetter": "C",
  "isManufacturer": true,
  "isShow": true,
  "logo": "logo1",
  "bigPic": "bigPic1",
  "sort": 100
}

### 删除品牌
DELETE http://localhost:9002/brands/12
Accept: application/json
Content-Type: application/json;charset=UTF-8

###
