### 获取所有商品属性分类
GET http://localhost:9002/productAttributeCategories
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 获取所有商品属性分类的参数设置
GET http://localhost:9002/productAttributeCategories/params
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 获取商品属性分类
GET http://localhost:9002/productAttributeCategories/1
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 分页获取所有商品属性分类
GET http://localhost:9002/productAttributeCategories/search/1/10
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 添加商品属性分类
POST http://localhost:9002/productAttributeCategories?name=cartisan
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 修改商品属性分类
PUT http://localhost:9002/productAttributeCategories/1?name=ca
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 删除商品属性分类
DELETE http://localhost:9002/productAttributeCategories/1
Accept: application/json
Content-Type: application/json;charset=UTF-8

###
