### 获取所有部门列表
GET http://localhost:8082/departments
Accept: application/json
Content-Type: application/json;charset=UTF-8

#### 获取部门
#GET http://localhost:8082/departments/1
#Accept: application/json
#Content-Type: application/json;charset=UTF-8
#
#### 搜索部门（不带参数）
#GET http://localhost:8082/departments/search/1/10
#Accept: application/json
#Content-Type: application/json;charset=UTF-8
#
#### 搜索部门
#GET http://localhost:8082/departments/search/1/10?name=car
#Accept: application/json
#Content-Type: application/json;charset=UTF-8

### 添加部门
POST http://localhost:8082/departments
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "研发中心",
  "parentId": 0,
  "remark": "研发中心研发核心产品",
  "sort": 100
}

### 添加子部门
POST http://localhost:8082/departments
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "前端开发组",
  "parentId": 1,
  "remark": "提高用户体验",
  "sort": 100
}

### 更新部门
PUT http://localhost:8082/departments/2
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "前端开发组",
  "parentId": 1,
  "remark": "要提高用户体验",
  "sort": 100
}

### 删除部门
DELETE http://localhost:8082/departments/12
Accept: application/json
Content-Type: application/json;charset=UTF-8

###
