#### 获取所有权限列表
#GET http://localhost:8082/permissions
#Accept: application/json
#Content-Type: application/json;charset=UTF-8

#### 获取权限
#GET http://localhost:8082/permissions/1
#Accept: application/json
#Content-Type: application/json;charset=UTF-8
#
#### 搜索权限（不带参数）
#GET http://localhost:8082/permissions/search/1/10
#Accept: application/json
#Content-Type: application/json;charset=UTF-8
#
### 搜索权限
GET http://localhost:8082/permissions/search/1/10??moduleId=1
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 添加权限
POST http://localhost:8082/permissions
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "研发中心",
  "parentId": 0,
  "remark": "研发中心研发核心产品",
  "sort": 100
}

### 添加子权限
POST http://localhost:8082/permissions
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "前端开发组",
  "parentId": 1,
  "remark": "提高权限体验",
  "sort": 100
}

### 更新权限
PUT http://localhost:8082/permissions/2
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "前端开发组",
  "parentId": 1,
  "remark": "要提高权限体验",
  "sort": 100
}

### 删除权限
DELETE http://localhost:8082/permissions/12
Accept: application/json
Content-Type: application/json;charset=UTF-8

###
