#### 获取所有用户列表
#GET http://localhost:8082/users
#Accept: application/json
#Content-Type: application/json;charset=UTF-8

#### 获取用户
#GET http://localhost:8082/users/1
#Accept: application/json
#Content-Type: application/json;charset=UTF-8
#
#### 搜索用户（不带参数）
#GET http://localhost:8082/users/search/1/10
#Accept: application/json
#Content-Type: application/json;charset=UTF-8
#
### 搜索用户
GET http://localhost:8082/users/search/1/10??departmentId=1
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 添加用户
POST http://localhost:8082/users
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "研发中心",
  "parentId": 0,
  "remark": "研发中心研发核心产品",
  "sort": 100
}

### 添加子用户
POST http://localhost:8082/users
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "前端开发组",
  "parentId": 1,
  "remark": "提高用户体验",
  "sort": 100
}

### 更新用户
PUT http://localhost:8082/users/2
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "name": "前端开发组",
  "parentId": 1,
  "remark": "要提高用户体验",
  "sort": 100
}

### 删除用户
DELETE http://localhost:8082/users/12
Accept: application/json
Content-Type: application/json;charset=UTF-8

###
