### 获取车型
GET http://localhost:9001/vehicle?countryId=78
Accept: application/json
Content-Type: application/json;charset=UTF-8

### 添加车型
POST http://localhost:9001/vehicle
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
	"code": "JP118",
    "name": "经济型25座",
    "description": "类似卡罗拉",
    "passengers": 3,
    "passengersDescription": null,
    "bigLuggage": 0,
    "smallLuggage": 2,
    "pictureUrl": null,
    "countryId": 78,
    "countryName": "日本"
}

### 修改车型
PUT http://localhost:9001/vehicle/31
Accept: application/json
Content-Type: application/json;charset=UTF-8

{
  "code": "JP120",
  "name": "经济型28座",
  "description": "类似卡罗拉",
  "passengers": 3,
  "passengersDescription": null,
  "bigLuggage": 0,
  "smallLuggage": 2,
  "pictureUrl": null,
  "countryId": 78,
  "countryName": "日本"
}

### 删除车型
DELETE http://localhost:9001/vehicle/31
Accept: application/json
Content-Type: application/json;charset=UTF-8

###
